version: "3.8"
services:
  app:
    build: ./
    container_name: todo
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm start"
    ports:
      - 3333:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - todo
  api:
    build: ./api
    container_name: node_api
    volumes:
      - ./api:/api
    working_dir: /api
    command: sh -c "npm start"
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    networks:
      - todo
  db:
    image: postgres:12
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: todo_db
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - todo

networks:
  todo: